project_id = "kisnmhcncgiwysbrcdkw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://kisnmhcncgiwysbrcdkw.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.generate-certificate]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.youtube-video-info]
verify_jwt = true