// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kisnmhcncgiwysbrcdkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpc25taGNuY2dpd3lzYnJjZGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTgyOTUsImV4cCI6MjA2NzQ5NDI5NX0.lGjTRuCPW3O4tKev8gD-o6GiELWYz9ZXElSuv_BpfhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});